### ISSUE TITLE
Kubernetes stable installation is broken 

### ISSUE THREAD

**Issue by kivarun** [openSUSE/cooverview#7] opened 2020-12-29 11:45 UTC
`        [ERROR ImagePull]: failed to pull image registry.opensuse.org/kubic/kube-apiserver:v1.18.12: output: time="2020-12-29T11:33:43Z" level=fatal msg="pulling image failed: rpc error: code = Unknown desc = Error choosing image instance: no image found in manifest list for architecture amd64, variant , OS linux"
, error: exit status 1`
Image for amd64 is disappeared from the registry 
kubernetes1.18-kubeadm
OpenSuse 15.2

**Comment by M0ses** [comment] 2021-05-06 07:49
Closing because this is no longer reproducible. 

In general, this is normally not a problem of cooverview itself - it might be caused by changes in the correlating OBS project (in hand of kubic/openSUSE maintainers - SEE https://build.opensuse.org/project/show/openSUSE:Containers:Tumbleweed).

This is not the right channel to report such issues.

Sorry for my delayed answer.

**Closed by M0ses** 2021-05-06 07:49 UTC
